// {
//   "user": {
//       "reporting_to": {
//           "email_id": "howard@mail.com"
//       },
//   }
// }
DEL USUARIO cristina.gonzalez@aguaquito.gob.ec
//NOMBRE DEL EMPLEADO
<ZNAME_EMP>ANGELA CRISTINA GONZALEZ CAMACHO</ZNAME_EMP>

//NUMERO DEL EMPLEADO O CODIGO
<N_EMPLEADO>00013234</N_EMPLEADO>

// CARGO DEL EMPLEADO
<ZTPLANS>GERENTE JURIDICO</ZTPLANS>

//DEPARTAMENTO
<ZTORGEH>GERENCIA JURIDICA</ZTORGEH>

//NUMERO DEPARTAMENTO
<ZORGEH>00290000</ZORGEH>

// NOMBRE DE LA GERENCIA
<ZTGEREN>GERENCIA JURIDICA</ZTGEREN>

//NOMBRE JEFE
<ZNAME_JF>TERESA VERONICA SANCHEZ HIDALGO</ZNAME_JF>

//CARGO DEL GERENTE
<ZTPLANS_JF>GERENTE GENERAL</ZTPLANS_JF>

//CORREO DEL GERENTE
<CORREO_JF>VERONICA.SANCHEZ@AGUAQUITO.GOB.EC</CORREO_JF>

/////////////////////////////////////////////////////////////
DEL USUARIO delia.nuniez@aguaquito.gob.ec
<ZNAME_EMP>DELIA MARIA NUNEZ TORRES</ZNAME_EMP>
<N_EMPLEADO>00013429</N_EMPLEADO>
<ZTGEREN>GERENCIA JURIDICA</ZTGEREN>
<ZORGEH>00290000</ZORGEH>
<ZTORGEH>GERENCIA JURIDICA</ZTORGEH>
<ZTPLANS>COORDINADOR DE GERENCIA</ZTPLANS>
<ZNAME_JF>ANGELA CRISTINA GONZALEZ CAMACHO</ZNAME_JF>
<ZTPLANS_JF>GERENTE JURIDICO</ZTPLANS_JF>
<CORREO_JF>CRISTINA.GONZALEZ@AGUAQUITO.GOB.EC</CORREO_JF>

DEL USUARIO guadalupe.padilla@aguaquito.gob.ec
<ZNAME_EMP>MARIA GUADALUPE PADILLA ALLAUCA</ZNAME_EMP>
<N_EMPLEADO>00003133</N_EMPLEADO>
<ZTGEREN>GERENCIA JURIDICA</ZTGEREN>
<ZORGEH>00290000</ZORGEH>
<ZTORGEH>GERENCIA JURIDICA</ZTORGEH>
<ZTPLANS>FUNCIONARIO 2 (SECRETARIA DE GERENCIA)</ZTPLANS>
<ZNAME_JF>ANGELA CRISTINA GONZALEZ CAMACHO</ZNAME_JF>
<ZTPLANS_JF>GERENTE JURIDICO</ZTPLANS_JF>
<CORREO_JF>CRISTINA.GONZALEZ@AGUAQUITO.GOB.EC</CORREO_JF>

DEL USUARIO ivan.vallejo@aguaquito.gob.ec
<ZNAME_EMP>IVAN OSWALDO VALLEJO AGUIRRE</ZNAME_EMP>
<N_EMPLEADO>00004050</N_EMPLEADO>
<ZORGEH>00290000</ZORGEH>
<ZTORGEH>GERENCIA JURIDICA</ZTORGEH>
<ZNAME_JF>ANGELA CRISTINA GONZALEZ CAMACHO</ZNAME_JF>
<ZTPLANS_JF>GERENTE JURIDICO</ZTPLANS_JF>
<CORREO_JF>CRISTINA.GONZALEZ@AGUAQUITO.GOB.EC</CORREO_JF>

